jobs:
  build:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      name: Set up Java 17
      uses: actions/setup-java@v4
      with:
        distribution: liberica
        java-version: 17
    - continue-on-error: true
      name: Build
      run: ./gradlew check
name: Build
on:
  repository_dispatch:
    types: trigger-ga___ci.yml
