jobs:
  build:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      id: build_info
      name: Build info
      run: 'BUILD_TAG=${GITHUB_REF#refs/tags/}

        cat ./CHANGELOG.md | grep "$BUILD_TAG" | sed ''s%^\*[[:space:]]*\*\*[0-9.]*\*\*[[:space:]]*%%g''
        > ${{ github.workspace }}-CHANGELOG.txt

        echo "build_tag=${BUILD_TAG}" >> $GITHUB_OUTPUT

        '
    - continue-on-error: true
      name: Set up Java 17
      uses: actions/setup-java@v4
      with:
        distribution: liberica
        java-version: 17
    - continue-on-error: true
      name: Build
      run: ./gradlew check buildPlugin
    - continue-on-error: true
      name: Release
      uses: softprops/action-gh-release@4634c16e79c963813287e889244c50009e7f0981
      with:
        body_path: ${{ github.workspace }}-CHANGELOG.txt
        draft: false
        files: build/distributions/CheckStyle-IDEA-${{ steps.build_info.outputs.build_tag
          }}.zip
        prerelease: false
    - continue-on-error: true
      env:
        JETBRAINS_PLUGIN_REPO_TOKEN: ${{ secrets.JETBRAINS_PLUGIN_REPO_TOKEN }}
      name: Publish to Jetbrains Plugin Repo
      run: ./gradlew publishPlugin
name: Release
on:
  repository_dispatch:
    types: trigger-ga___release.yml
